'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
    Lightbulb,
    TrendingUp,
    AlertTriangle,
    CheckCircle2,
    ArrowRight,
    Sparkles,
    Target,
    BookOpen,
} from 'lucide-react';
import { cn } from '@/lib/utils';

interface Insight {
    id: string;
    type: 'quality' | 'citation' | 'methodology' | 'direction' | 'gap';
    title: string;
    description: string;
    priority: 'high' | 'medium' | 'low';
    actionable: boolean;
    action?: string;
}

interface ProjectInsightsProps {
    projectId: string;
}

export function ProjectInsights({ projectId }: ProjectInsightsProps) {
    // In a real implementation, these would be generated by an AI agent analyzing the project
    const insights: Insight[] = [
        {
            id: '1',
            type: 'quality',
            title: 'Improve Abstract Clarity',
            description: 'The abstract could be more concise. Consider reducing from 250 to 200 words while maintaining key points.',
            priority: 'high',
            actionable: true,
            action: 'Revise Abstract'
        },
        {
            id: '2',
            type: 'citation',
            title: 'Citation Gap Detected',
            description: 'Missing citations for recent work (2023-2024) in the related work section. Found 5 highly relevant papers.',
            priority: 'high',
            actionable: true,
            action: 'Add Citations'
        },
        {
            id: '3',
            type: 'methodology',
            title: 'Strengthen Methodology Section',
            description: 'Consider adding more details about data collection procedures and validation methods to improve reproducibility.',
            priority: 'medium',
            actionable: true,
            action: 'Enhance Methodology'
        },
        {
            id: '4',
            type: 'direction',
            title: 'Promising Research Direction',
            description: 'Your hypothesis about combining neural networks with symbolic reasoning aligns with emerging trends. Consider expanding this angle.',
            priority: 'medium',
            actionable: false,
        },
        {
            id: '5',
            type: 'gap',
            title: 'Literature Gap Opportunity',
            description: 'Limited work exists on applying your approach to multi-modal data. This could be a strong contribution angle.',
            priority: 'low',
            actionable: false,
        },
    ];

    const getInsightIcon = (type: Insight['type']) => {
        switch (type) {
            case 'quality':
                return <Sparkles className="w-5 h-5 text-primary" />;
            case 'citation':
                return <BookOpen className="w-5 h-5 text-blue-500" />;
            case 'methodology':
                return <Target className="w-5 h-5 text-purple-500" />;
            case 'direction':
                return <TrendingUp className="w-5 h-5 text-green-500" />;
            case 'gap':
                return <Lightbulb className="w-5 h-5 text-yellow-500" />;
        }
    };

    const getPriorityBadge = (priority: Insight['priority']) => {
        switch (priority) {
            case 'high':
                return <Badge variant="destructive" className="gap-1">
                    <AlertTriangle className="w-3 h-3" />
                    High Priority
                </Badge>;
            case 'medium':
                return <Badge variant="secondary">Medium Priority</Badge>;
            case 'low':
                return <Badge variant="outline">Low Priority</Badge>;
        }
    };

    const highPriorityCount = insights.filter(i => i.priority === 'high').length;

    return (
        <Card className="shadow-premium">
            <CardHeader>
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                    <div>
                        <CardTitle className="flex items-center gap-2">
                            <Lightbulb className="w-5 h-5 text-primary" />
                            AI-Generated Insights
                        </CardTitle>
                        <CardDescription>
                            Intelligent recommendations to improve your research
                        </CardDescription>
                    </div>
                    {highPriorityCount > 0 && (
                        <Badge variant="destructive" className="gap-1">
                            {highPriorityCount} High Priority
                        </Badge>
                    )}
                </div>
            </CardHeader>
            <CardContent>
                <div className="space-y-4">
                    {insights.map((insight, index) => (
                        <div
                            key={insight.id}
                            className={cn(
                                'p-4 rounded-lg border bg-card hover:shadow-md transition-all animate-fadeIn',
                                insight.priority === 'high' && 'border-destructive/30 bg-destructive/5'
                            )}
                            style={{ animationDelay: `${index * 0.1}s` }}
                        >
                            <div className="flex items-start gap-3">
                                <div className="mt-0.5">
                                    {getInsightIcon(insight.type)}
                                </div>
                                <div className="flex-1 min-w-0">
                                    <div className="flex items-start justify-between gap-2 mb-2">
                                        <h4 className="font-semibold text-sm">
                                            {insight.title}
                                        </h4>
                                        {getPriorityBadge(insight.priority)}
                                    </div>
                                    <p className="text-sm text-muted-foreground mb-3">
                                        {insight.description}
                                    </p>
                                    {insight.actionable && insight.action && (
                                        <Button
                                            variant="outline"
                                            size="sm"
                                            className="gap-2"
                                        >
                                            {insight.action}
                                            <ArrowRight className="w-3 h-3" />
                                        </Button>
                                    )}
                                    {!insight.actionable && (
                                        <div className="flex items-center gap-1 text-xs text-muted-foreground">
                                            <CheckCircle2 className="w-3 h-3" />
                                            Informational - No action required
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </CardContent>
        </Card>
    );
}
